default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: getlinks_test_development

test:
  <<: *default
  database: getlinks_test_test

production:
  <<: *default
  database: getlinks_test_production
